config_csv_data = "D:/CodeResp/IRBOPP/train/halpe26_reid/iou06/"
config_jaad_clip = "D:/CodeResp/jaad_data/JAAD_clips/"
config_jaad_img = "D:/CodeResp/jaad_data/JAAD_image/"
config_jaad_anno = "D:/CodeResp/jaad_data/JAAD/annotations/"
config_alpha_pose = "D:/CodeResp/jaad_data/AlphaReidResultNoFast/"
